server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_n_1_problem
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    drop-first: true
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hibernate_n_1_problem
    password: postgres
    user: postgres